name: Release

on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 21
          cache: npm
      - run: npm ci

      - name: Test build package on node@21 (current)
        run: |
          node --version
          npm --version
          npm run test

      # Not using a matrix here since it's simpler
      # to just duplicate it and not spawn new instances
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
      - name: test build package on node@20 (LTS)
        run: |
          node --version
          npm --version
          npm run test

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18
      - name: test build package on node@18 (LTS)
        run: |
          node --version
          npm --version
          npm run test

      - name: Build package
        run: npm run build

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: '>=20.8.1'
          cache: 'npm'

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

      - name: Test Outputs of Semantic Release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Push updates to branch for major version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: 'git push https://x-access-token:${{ secrets.REGISTRY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:refs/heads/v${{ steps.semantic.outputs.new_release_major_version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
