name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
      - run: npm ci

      - name: Test build package on node@21 (current)
        run: |
          node --version
          npm --version
          npm run test

      # Not using a matrix here since it's simpler
      # to just duplicate it and not spawn new instances
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: test build package on node@20 (LTS)
        run: |
          node --version
          npm --version
          npm run test

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: test build package on node@18 (LTS)
        run: |
          node --version
          npm --version
          npm run test

      - name: Build package
        run: npm run build

      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.8.1' 
          cache: 'npm'

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
        run: npx semantic-release
